name             'barbican-base'
maintainer       'Rackspace, Inc.'
maintainer_email 'john.wood@rackspace.com'
license          'Apache License, Version 2.0'
description      'Installs/Configures barbican-base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.7'
depends          'yum', '>= 2.3.2'
depends          'newrelic'
depends          'python'
