language: ruby
bundler_args: --without development
script: "bundle exec rake build"
rvm:
  - 2.0.0
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
script:
  - bundle exec knife inspect
  - bundle exec knife test
