# Torque directories
default['torque']['etc_dir'] = '/etc/torque'

case node['platform_family']
when 'debian'
  default['torque']['var_dir'] = '/var/spool/torque'
when 'rhel', 'fedora'
  default['torque']['var_dir'] = '/var/lib/torque'
end

# Public key - generated by the head node
default['torque']['publickey'] = 'not found'

# Torque user
default['torque']['user'] = 'pbs'

# Queue setup
default['torque']['manager_host'] = node['fqdn']
default['torque']['acl_hosts'] = node['fqdn']
default['torque']['server_scheduling'] = 'true'
default['torque']['keep_completed'] = '300'
default['torque']['mom_job_sync'] = 'pbs'
default['torque']['queue'] = 'batch'
default['torque']['queue_type'] = 'execution'
default['torque']['started'] = 'true'
default['torque']['enabled'] = 'true'
default['torque']['walltime'] = '1:00:00'
default['torque']['auto_node_np'] = 'true'
default['torque']['default_queue'] = 'pbs'

