driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-10.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[ntp::default]
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
  - name: undo
    run_list:
      - recipe[ntp::undo]
